library/build.gradle
library/java/net/openid/appauth/AuthorizationRequest.java
library/java/net/openid/appauth/AuthorizationService.java
library/java/net/openid/appauth/UriUtil.java
library/javatests/net/openid/appauth/AuthorizationRequestTest.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/1)

Move request URI generation into AuthorizationRequest

---

build.gradle

The build script was trying to populate the auto-generated keystore
with the right user name in the CN= field, by retrieving the user's
name from the git config. With some configurations, this just plain
won't work. So, don't try and be so clever, just use "appauth" as
the name, given it is of no real consequence.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/5)

Don't try and directly invoke git in builds

---

library/java/net/openid/appauth/BrowserPackageHelper.java
library/javatests/net/openid/appauth/BrowserPackageHelperTest.java

PackageManager.queryIntentActivities is documented as always returning
matching activities in a priority order, such that the default match
would always be returned first. Therefore, we do not need to
separately handle default browsers: scanning in order and recording
the first "full" browser will have the same effect in all cases that
matter.
Should fix #3.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/4)

Fix browser package scanning

---

library/java/net/openid/appauth/AuthorizationException.java
library/java/net/openid/appauth/AuthorizationRequest.java
library/java/net/openid/appauth/AuthorizationServiceDiscovery.java
library/java/net/openid/appauth/BrowserPackageHelper.java
library/java/net/openid/appauth/JsonUtil.java
library/java/net/openid/appauth/Logger.java
library/java/net/openid/appauth/TokenRequest.java
library/java/net/openid/appauth/TokenResponse.java

- Tighten up scoping / Annotate @VisibleForTesting
- Use Preconditions static imports consistently
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/7)

Codacy errorprone report warning fixes

---

library/java/net/openid/appauth/AuthState.java
library/javatests/net/openid/appauth/AuthStateTest.java
library/javatests/net/openid/appauth/TestValues.java

@WilliamDenniss - testing uncovered some subtle bugs around our utility methods for tokens and token expiry, where tokens returned on the authorization response can be hidden by those on subsequent token responses. I don't know if this is a real problem, but I think the spec seems flexible in this regard. So, I made some changes to check the auth response for a token value if it is not found on the token response.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/35) &emsp; Multiple assignees:&emsp;<img alt="@WilliamDenniss" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/445150?s=40&v=3">&nbsp;<a …

Test coverage and fixes for AuthState

---

library/java/net/openid/appauth/AuthorizationService.java
library/java/net/openid/appauth/TokenRequest.java
library/javatests/net/openid/appauth/AuthorizationServiceTest.java
library/javatests/net/openid/appauth/TokenRequestTest.java

The URI used for token requests was previously build from components of the actual URI provided by the provider configuration. This was partly through being over-opinionated about the structure of token URIs, but also to avoid mixing any parameters set on the token URI with those that would ultimately have been sent in the request body, as a side-effect of the way the body was being constructed. This decouples the two concerns, allowing the token URI to be used as-is from the configuration, while building the request body using a clean URI builder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/37) &emsp; Multiple assignees:&emsp;<img alt="@WilliamDenniss" …

Be less opinionated about the token request URI

---

app/src/net/openid/appauthdemo/IdentityProvider.java
app/src/net/openid/appauthdemo/MainActivity.java
library/java/net/openid/appauth/AuthState.java
library/java/net/openid/appauth/AuthorizationException.java
library/java/net/openid/appauth/AuthorizationRequest.java
library/java/net/openid/appauth/AuthorizationResponse.java
library/java/net/openid/appauth/AuthorizationService.java
library/java/net/openid/appauth/AuthorizationServiceConfiguration.java
library/java/net/openid/appauth/GrantTypeValues.java
library/java/net/openid/appauth/JsonUtil.java
library/java/net/openid/appauth/Preconditions.java
library/java/net/openid/appauth/RegistrationRequest.java
library/java/net/openid/appauth/RegistrationResponse.java
library/java/net/openid/appauth/ResponseTypeValues.java
library/java/net/openid/appauth/TokenRequest.java
library/javatests/net/openid/appauth/AuthStateTest.java
library/javatests/net/openid/appauth/AuthorizationRequestTest.java
library/javatests/net/openid/appauth/AuthorizationServiceConfigurationTest.java
library/javatests/net/openid/appauth/AuthorizationServiceTest.java
library/javatests/net/openid/appauth/PreconditionsTest.java
library/javatests/net/openid/appauth/RegistrationRequestTest.java
library/javatests/net/openid/appauth/RegistrationResponseTest.java
library/javatests/net/openid/appauth/TestValues.java
library/javatests/net/openid/appauth/TokenRequestTest.java

A basis for implementation of OIDC dynamic client registration according to [specs](https://openid.net/specs/openid-connect-registration-1_0.html).
What's done:
* Registration Request/Registration Response representation.
* AsyncTask for sending the request.
* Example in the demo app of how it can be used.
Still missing:
* Documentation/references to the valid sections of the specification.
* Maybe this could be generalized to also support [OAuth 2.0 Dynamic client registration](https://tools.ietf.org/html/rfc7591). I haven't verified how far off it might be.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/40)

[WIP] OpenID Connect Dynamic Client Registration support

---

app/src/net/openid/appauthdemo/MainActivity.java
app/src/net/openid/appauthdemo/TokenActivity.java
library/java/net/openid/appauth/AuthorizationService.java
library/java/net/openid/appauth/ClientAuthentication.java
library/java/net/openid/appauth/ClientSecretBasic.java
library/java/net/openid/appauth/ClientSecretPost.java
library/java/net/openid/appauth/GrantTypeValues.java
library/java/net/openid/appauth/NoClientAuthentication.java
library/java/net/openid/appauth/RegistrationRequest.java
library/java/net/openid/appauth/RegistrationResponse.java
library/java/net/openid/appauth/ResponseTypeValues.java
library/java/net/openid/appauth/TokenRequest.java
library/java/net/openid/appauth/UriUtil.java
library/javatests/net/openid/appauth/AuthorizationServiceTest.java
library/javatests/net/openid/appauth/ClientSecretBasicTest.java
library/javatests/net/openid/appauth/ClientSecretPostTest.java
library/javatests/net/openid/appauth/NoClientAuthenticationTest.java
library/javatests/net/openid/appauth/RegistrationRequestTest.java
library/javatests/net/openid/appauth/RegistrationResponseTest.java
library/javatests/net/openid/appauth/TokenRequestTest.java
library/javatests/net/openid/appauth/UriUtilTest.java

(This branch is based off PR #40, so the relevant diff is [here](https://github.com/rebeckag/AppAuth-Android/compare/oidc-dynreg...rebeckag:client-auth).)
Implementation of 'client_secret_basic' and 'client_secret_post' per [specs](http://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication).
What's done:
* Representation for different ClientAuthentication methods.
* Added possibility to specify client authentication in AsyncTask for TokenRequest.
* Example in the demo app of how it could be used.
Still left:
* Documentation/references to the valid sections of the specification.
* Maybe figure out better design for how the client authentication is applied in TokenRequestTask.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …

[WIP] Support client authentication at token endpoint

---

app/src/net/openid/appauthdemo/TokenActivity.java
library/java/net/openid/appauth/AuthState.java
library/java/net/openid/appauth/AuthorizationRequest.java
library/java/net/openid/appauth/AuthorizationResponse.java
library/java/net/openid/appauth/RegistrationRequest.java
library/java/net/openid/appauth/RegistrationResponse.java
library/java/net/openid/appauth/TokenRequest.java
library/java/net/openid/appauth/TokenResponse.java
library/javatests/net/openid/appauth/AuthStateTest.java
library/javatests/net/openid/appauth/AuthorizationRequestTest.java
library/javatests/net/openid/appauth/AuthorizationResponseTest.java
library/javatests/net/openid/appauth/RegistrationRequestTest.java
library/javatests/net/openid/appauth/RegistrationResponseTest.java

Suggestion by @rebeckag, to clarify which methods are specifically for local serialization vs the JSON formats that are part of the spec for transmission to / reception from authorization servers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/53)

Normalize names and documentation of JSON serialization methods

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/54)

Remove build version hack required for older android gradle plugin

---

library/java/net/openid/appauth/AuthorizationRequest.java
library/java/net/openid/appauth/Preconditions.java
library/javatests/net/openid/appauth/AuthorizationRequestTest.java
library/javatests/net/openid/appauth/PreconditionsTest.java
library/javatests/net/openid/appauth/TokenRequestTest.java

This also fixed the prompt serialization issue, by paying closer
attention to the builder, toUri and serialization behavior of
each parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/59)

Split AuthorizationRequest tests into smaller units

---

README.md

`AuthorizationService.performAuthorizationRequest` expects a `PendingIntent` instead of a plain `Intent`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/69)

Pass PendingIntent to performAuthorizationRequest.

---

app/src/net/openid/appauthdemo/IdentityProvider.java
app/src/net/openid/appauthdemo/MainActivity.java
app/src/net/openid/appauthdemo/TokenActivity.java
library/java/net/openid/appauth/AuthState.java
library/java/net/openid/appauth/ClientAuthentication.java
library/java/net/openid/appauth/RegistrationResponse.java
library/javatests/net/openid/appauth/AuthStateTest.java
library/javatests/net/openid/appauth/RegistrationResponseTest.java
library/javatests/net/openid/appauth/TestValues.java

Make use of the stored RegistrationResponse when constructing token requests in the TokenActivity of the demo app.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/61)

Store RegistrationResponse in AuthState.

---

library/java/net/openid/appauth/AuthorizationServiceConfiguration.java
library/javatests/net/openid/appauth/AuthorizationServiceConfigurationTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/73)

Fix #72 - avoid path encoding in config URIs

---

build.gradle
library/build.gradle
library/javatests/net/openid/appauth/AsciiStringListUtilTest.java
library/javatests/net/openid/appauth/AuthStateTest.java
library/javatests/net/openid/appauth/AuthorizationRequestTest.java
library/javatests/net/openid/appauth/AuthorizationResponseTest.java
library/javatests/net/openid/appauth/AuthorizationServiceConfigurationTest.java
library/javatests/net/openid/appauth/AuthorizationServiceDiscoveryTest.java
library/javatests/net/openid/appauth/AuthorizationServiceTest.java
library/javatests/net/openid/appauth/BrowserPackageHelperTest.java
library/javatests/net/openid/appauth/JsonUtilTest.java
library/javatests/net/openid/appauth/LoggerTest.java
library/javatests/net/openid/appauth/PendingIntentStoreTest.java
library/javatests/net/openid/appauth/PreconditionsTest.java
library/javatests/net/openid/appauth/RedirectUriReceiverActivityTest.java
library/javatests/net/openid/appauth/TokenRequestTest.java
library/javatests/net/openid/appauth/TokenResponseTest.java
library/javatests/net/openid/appauth/UtilsTest.java

We can't use 3.0 as it doesn't support API v23, so we have to use 3.1-SNAPSHOT until an official release comes out :/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/39)

Update Robolectric version

---

CONTRIBUTING.md

Just a text suggestion to clarify the existence of the gradle `check` target in the contribution guidelines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/84)

Add note about gradle check target in contribution guidelines.

---

library/java/net/openid/appauth/JsonUtil.java

This pull request is focused on resolving occurrences of Sonar rules squid:S1319 - Declarations should use Java collection interfaces such as "List" rather than specific implementation classes such as "LinkedList"
You can find more information about the issues here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1319
Please let me know if you have any questions.
M-Ezzat
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/70)

Multiple quality improvements

---

library/java/net/openid/appauth/AuthorizationServiceConfiguration.java
library/javatests/net/openid/appauth/AuthorizationServiceConfigurationTest.java

Fixes #88: since the registration endpoint is not required by the spec, it might not be set when trying to deserialize a serialized representation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/92)

Fix for issue #88: handle missing registration endpoint

---

library/java/net/openid/appauth/AuthState.java
library/javatests/net/openid/appauth/AuthStateTest.java

Whether we have a refresh token or not is irrelevant for determining
if the access token is valid. The case where the access token has
expired and we have no refresh token is already signalled as an error
to the callback in performActionWithFreshTokens.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/93)

Disregard refresh token when deciding if access token is still fresh.

---

library/java/net/openid/appauth/AuthorizationException.java
library/java/net/openid/appauth/AuthorizationManagementActivity.java
library/javatests/net/openid/appauth/AuthorizationManagementActivityTest.java

Failing to check the state was a regression introduced by the change from using a static store of requests to the AuthorizationManagementActivity - this is now corrected, with tests added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/111)

Ensure state param in response matches request

---

library/java/net/openid/appauth/AppAuthConfiguration.java
library/java/net/openid/appauth/AuthorizationService.java
library/java/net/openid/appauth/AuthorizationServiceConfiguration.java
library/java/net/openid/appauth/connectivity/ConnectionBuilder.java
library/java/net/openid/appauth/connectivity/DefaultConnectionBuilder.java
library/java/net/openid/appauth/connectivity/package-info.java
library/javatests/net/openid/appauth/AuthorizationServiceConfigurationTest.java
library/javatests/net/openid/appauth/AuthorizationServiceTest.java

This allows a number of use cases:
- Disabling HTTPS checks for debug environments
- Configuring certificate pinning
- Using a different HTTP stack, such as okhttp or cronet
Fixes #115.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/120)

Introduce ability to control creation of HttpUrlConnection instances

---

app/java/net/openid/appauthdemo/BrowserSelectionAdapter.java
app/java/net/openid/appauthdemo/MainActivity.java
app/res/layout/activity_main.xml
app/res/layout/browser_selector_layout.xml
app/res/values/strings.xml
library/AndroidManifest.xml
library/java/net/openid/appauth/AuthorizationManagementActivity.java
library/java/net/openid/appauth/AuthorizationService.java
library/java/net/openid/appauth/browser/BrowserDescriptor.java
library/java/net/openid/appauth/browser/BrowserSelector.java
library/java/net/openid/appauth/browser/ExactBrowserMatcher.java
library/javatests/net/openid/appauth/browser/BrowserDescriptorTest.java

This change adds the ability to explicitly choose the browser to use in the demo app, making it easier to test the authorization flow against specific browsers. This uncovered an issue in AuthorizationManagementActivity when using a standalone browser:
- `launchMode=singleTask` is required to ensure that the correct activity instance is reached. This also has the side effect that only one browser-based interaction can happen at a time, but this is a reasonable assumption for the library to make.
- Failing to find stored state for handling a redirect no longer causes an IllegalStateException, and instead simply finishes the management activity. This can happen where the user switches back and forth between the app and browser, resulting in the flow being cancelled and then resumed after …

Fixes and manual test capability for browser selection

---

library/java/net/openid/appauth/AuthorizationService.java
library/javatests/net/openid/appauth/AuthorizationServiceTest.java

If the response code is a non 200, use conn.getErrorStream instead.
This will allow things like token refresh errors to be handled correctly.
Currently, you get an AuthorizationException with a FileNotFoundException
as it's cause due to the call to conn.getInputStream.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/144)

Check Response Code before using conn.getInputStream

---

library/java/net/openid/appauth/AuthorizationService.java
library/javatests/net/openid/appauth/AuthorizationServiceTest.java

With the changes to retain way the browser intent is launched
in recent versions (AuthorizationManagementActivity etc.) it
is now possible to retain custom tabs on the back stack, which
provides a better experience when switching apps in the middle
of an authorization flow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/150)

Allow custom tab to remain in back stack

---

library/java/net/openid/appauth/AuthorizationService.java
library/javatests/net/openid/appauth/AuthorizationServiceTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/156)

Allow proper error parsing with no error_description is given.

---

library/java/net/openid/appauth/AuthorizationService.java

while servers should expect and only accept json bodies some parsers out there would not parse the body without an appropriate content-type being set
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/180)

set content-type for dynamic registration request

---

library/java/net/openid/appauth/AuthorizationService.java
library/javatests/net/openid/appauth/AuthorizationServiceTest.java

Reintroduce this header, which was accidentally removed after #41. This is primarily for GitHub, which is not spec compliant, but is harmless to other IDPs so there is no real reason not include it.
Fixes #174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/175)

Add "Accept: application/json" to token requests

---

app/AndroidManifest.xml
app/build.gradle
app/res/values/strings.xml

Jack is now deprecated:
https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html
In order to continue to support Java 8 features in the demo app,
retrolambda is temporarily introduced until official Java 8 support
is provided in the Android SDK.
Fixes #190.

Disable Jack compiler

---

library/java/net/openid/appauth/AuthState.java
library/java/net/openid/appauth/AuthorizationService.java
library/javatests/net/openid/appauth/AuthStateTest.java

Based on the discussion in #178, allow client authentication method override
for calls to `performActionWithFreshTokens`. Fixes #179.

Allow explicit client authentication for fresh tokens

---

library/java/net/openid/appauth/ClientAuthentication.java
library/java/net/openid/appauth/ClientSecretBasic.java
library/java/net/openid/appauth/ClientSecretPost.java
library/java/net/openid/appauth/NoClientAuthentication.java
library/java/net/openid/appauth/TokenRequest.java
library/java/net/openid/appauth/UriUtil.java
library/javatests/net/openid/appauth/AuthorizationServiceTest.java
library/javatests/net/openid/appauth/NoClientAuthenticationTest.java
library/javatests/net/openid/appauth/TokenRequestTest.java

Fixes #181 - NoClientAuthentication now adds the client ID explicitly,
rather than adding it to every token request, which fixes the issue
with ClientSecretBasic. ClientSecretPost was explicitly adding
client_id anyway, so no new issues introduced there.

Do not add client_id by default on all token requests

---

library/build.gradle

I have the permissions required to start syncing our library to Maven Central. In order for this to work, we need extra information injected into our POM file.

Maven central sync settings

---

library/java/net/openid/appauth/RegistrationResponse.java
library/java/net/openid/appauth/TokenResponse.java
library/javatests/net/openid/appauth/AuthStateTest.java
library/javatests/net/openid/appauth/RegistrationResponseTest.java
library/javatests/net/openid/appauth/TokenResponseTest.java

The deserialization for RegistrationResponse and TokenResponse was incorrectly copying the associated request into the "additionalParameters" map on each deserialize, resulting in exponential growth of the JSON with each subsequent serialize / deserialize operation.
Fixes #224, though clients will have to clear the additionalParameters map of unwanted properties manually, as I do not want to assume what properties are and are not being used in the map.

Fix JSON deserialization

---

library/java/net/openid/appauth/TokenResponse.java
library/javatests/net/openid/appauth/TokenResponseTest.java

Error handling on the parsing of authorization and token responses generally
needs an overhaul to ensure we can more reliably catch data validation errors;
this just fixes one specific issue. Bigger changes will be deferred for the
0.7.0 release.
Fix for #228.

Throw JSONException if token_type field is missing from token response

---

library/java/net/openid/appauth/AuthorizationServiceConfiguration.java

[Rebase of #138]
Add new constructor for the far more common case of a configuration
that does not use Dynamic Client Registration Protocol.

Add simpler AuthorizationServiceConfiguration constructor

---

app/java/net/openid/appauthdemo/AuthStateManager.java

The method writeState did not really write the state to the SharePreferences, but only removed the entry if the supplied state was null.

Actually write new AuthState to SharedPreferences

---

build.gradle

Fixes minor typo in `build.gradle` for a rare (if not impossible) error scenario. Just for correctness 😉

Fix minor gradle typo

---

app/java/net/openid/appauthdemo/LoginActivity.java
app/res/layout/activity_login.xml
app/res/values/strings.xml
library/java/net/openid/appauth/AuthorizationManagementActivity.java
library/java/net/openid/appauth/AuthorizationService.java
library/javatests/net/openid/appauth/AuthorizationManagementActivityTest.java
library/javatests/net/openid/appauth/AuthorizationServiceTest.java

As a simpler way to use AppAuth, offers a way to retrieve an intent
for use with startActivityForResult, where the authorization result 
is returned to the calling activity via onActivityResult().

Implement startActivityForResult based auth flow.

---

README.md
library/java/net/openid/appauth/AuthorizationManagementActivity.java
library/javatests/net/openid/appauth/AuthorizationManagementActivityTest.java

To ensure consistency across completion and cancelation flows, an AuthorizationException will be encoded into the cancelation response (via pending intent or activity result) to ensure a response or exception is always available.
The main README is also updated to cover the new way to trigger the authorization flow, using an Intent.

Return exception on cancelation, update README

---

library/java/net/openid/appauth/AuthorizationService.java

Use of startActivityForResult with activities marked as singleTask only reliably works after Android Lollipop, so marking these methods as a warning. If required, a solution will be found for broader compatibility.

Mark intent methods with @TargetApi(21)

---

app/java/net/openid/appauthdemo/Configuration.java
app/java/net/openid/appauthdemo/TokenActivity.java
app/res/raw/auth_config.json

As a fix to the issue "User info endpoint configuration is only possible through the discovery url" at  https://github.com/openid/AppAuth-Android/issues/270 I have created this fix. With this fix it is possible to manually configure a user info endpoint if the auto configuration is not an option.

Configurable user info endpoint location

---

library/java/net/openid/appauth/AuthState.java
library/javatests/net/openid/appauth/AuthStateTest.java

This fixes issue #309 by maintaining a collection of pending actions when multiple performActionWithFreshTokens calls have been made but the access token has expired. Issue #309 occurs when the second request hits the authorization server, the refresh token contained in the TokenRequest does not match the refresh token on the auth server. Now instead of making multiple TokenRequests, it appends the action to a list of pending actions, and when the first TokenRequest returns from auth server, it executes all of the pending actions using the one TokenResponse for all of them.

Synchronizes multiple actions when requiring token refresh

---

library/java/net/openid/appauth/JsonUtil.java
library/java/net/openid/appauth/TokenResponse.java

This commit stops token responses from failing to parse when an `expires_at` field is not a long. This is true for Sentry.io's OAuth2 implementation, which responds with an ISO date string for that field, and as this field is not defined in the OAuth 2 RFC, there is no reason for this field to be strictly handled.

Make handling of non-standard expires_at more tolerant

---

library/build.gradle

Apparently manifest placeholder processing has changed in recent android gradle plugin versions, such that the test value specified for the library is now taking precedence over values specified for the demo app project. This change fixes the issue by creating a new build type that the unit tests use, where the manifest placeholder can be independently changed.

Fix manifest placeholder processing

---

library/java/net/openid/appauth/ClientSecretBasic.java
library/java/net/openid/appauth/internal/UriUtil.java
library/javatests/net/openid/appauth/ClientSecretBasicTest.java

Fixes the encoding of client ids and secrets when performing client
secret basic auth.

Fix encoding of client ids and secrets for auth

---

CONTRIBUTORS
library/java/net/openid/appauth/browser/BrowserBlacklist.java
library/java/net/openid/appauth/browser/BrowserSelector.java
library/java/net/openid/appauth/browser/Browsers.java
library/java/net/openid/appauth/browser/VersionedBrowserMatcher.java
library/javatests/net/openid/appauth/browser/BrowserSelectorTest.java
library/javatests/net/openid/appauth/browser/BrowserWhitelistTest.java

a possible default browser of the user is respected.
fixes: #372
split from https://github.com/openid/AppAuth-Android/pull/369
Signed-off-by: Henning Nielsen Lund <henning.n.lund@jp.dk>

Respect default browser of the user

---

CONTRIBUTORS
library/java/net/openid/appauth/browser/Browsers.java
library/java/net/openid/appauth/browser/VersionedBrowserMatcher.java
library/javatests/net/openid/appauth/browser/AnyBrowserMatcherTest.java
library/javatests/net/openid/appauth/browser/BrowserWhitelistTest.java

At the moment all versions of the Samsung Internet Browser is set to support Custom Tabs. Support for Custom Tabs was first added in version 4.0.
fixes: #382
Signed-off-by: Henning Nielsen Lund <henning.n.lund@jp.dk>

Custom Tabs was first added in Samsung Internet 4.0

---

library/java/net/openid/appauth/AuthorizationService.java
library/javatests/net/openid/appauth/AuthorizationServiceTest.java

Make it possible to get the BrowserDescriptor used by AuthorizationService.
fixes: #387
Signed-off-by: Henning Nielsen Lund <henning.n.lund@jp.dk>

add getBrowserDescriptor()

---

library/java/net/openid/appauth/browser/BrowserSelector.java

* This helps with the jetification. I produced an artifact locally,
and wrote a sample app using:
```gradle
implementation 'androidx.appcompat:appcompat:1.0.0-rc02'
implementation 'androidx.browser:browser:1.0.0-rc02'
```
to make sure that the app works.
Fixes: https://github.com/openid/AppAuth-Android/issues/395

Use CustomTabsService.ACTION_CUSTOM_TABS_CONNECTION in BrowserSelector.

---

library/java/net/openid/appauth/Utils.java
library/javatests/net/openid/appauth/UtilsTest.java

- fixes NPE by checking for null and throwing an IOException instead

Issue #402: fixes NPE in case input stream is null

---

README.md

The snippet code in the `Using access tokens` section didn't follow java code formatting.

Fix `Using access tokens` snippet in the readme

---

README.md

- include outer class name, AuthorizationServiceConfiguration, as most
IDEs prefer that (and that's how it's used in
AuthorizationServiceConfigurationTest too)
- make visibility of onFetchConfigurationCompleted public to make it's
definition in the RetrieveConfigurationCallback interface (which
although unspecified defaults to public in an interface)
- fetchFromIssuer returns void so don't attempt to assign it anywhere

Update fetchFromIssuer example in README.md

---

README.md
app/AndroidManifest.xml
library/AndroidManifest.xml
library/java/net/openid/appauth/browser/BrowserSelector.java

While this item was addressed in https://github.com/openid/AppAuth-Android/pull/558/ having integrators manually add the query is not ideal.
This PR adds the query in the library manifest and lets the compile process merge it in the resulting package removing the extra integration step.
Thanks for @chrisbanes for also raising awareness on the topic in https://github.com/openid/AppAuth-Android/issues/599
To note that checking BROWSABLE is enough, as Custom Tabs is just a subset of those packages : https://developer.android.com/training/basics/intents/package-visibility-use-cases#check-browser-available

Add package visibility manifest query for accessing browsers on sdk 30

---

library/java/net/openid/appauth/AuthState.java

This change provides parity with AppAuth-iOS.  See this PR for more details (https://github.com/openid/AppAuth-iOS/pull/301).

Set scope to null when refreshing the token

---

library/java/net/openid/appauth/AuthorizationServiceConfiguration.java
library/java/net/openid/appauth/AuthorizationServiceDiscovery.java
library/javatests/net/openid/appauth/AuthorizationServiceConfigurationTest.java

End-session support (#525) introduced a new parameter to AuthorizationServiceConfiguration and broke backwards compatibility.
This change restores registrationEndpoint to 3rd position in constructor and reintroduces the 3 parameter constructor.
Thanks @chrisbanes for noticing.

Restore backwards compatible of configuration constructor

---

library/java/net/openid/appauth/AppAuthConfiguration.java
library/java/net/openid/appauth/AuthorizationService.java
library/java/net/openid/appauth/IdToken.java
library/javatests/net/openid/appauth/IdTokenTest.java

Change aims to address issue in #655, #585 and #657 by adding the ability to disable certain steps in ID Token validation.

Add ability to skip issuer https check and token nonce verification

---

library/java/net/openid/appauth/IdToken.java

`max_age` rules should be `rules #13` according to https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation

Fix idToken validation rules reference

---

app/java/net/openid/appauthdemo/TokenActivity.java

Userinfo endpoint call does not honor https_required configuration, which is done for token endpoint call.
Resolves https://github.com/openid/AppAuth-Android/issues/467

Use ConnectionBuilder to call userinfo endpoint

---

README.md

Had an issue using this library for the first time by forgetting to update the persisted authstate after using fresh tokens, especially when integrating with services that have single-use refresh tokens.
Adds a note to the documentation to help people know that this is required.

Add note to README.md to remind about persisting fresh tokens
