- library/java/net/openid/appauth/AuthorizationService.java
- library/java/net/openid/appauth/TokenRequest.java
- library/java/net/openid/appauth/UriUtil.java
- library/javatests/net/openid/appauth/AuthorizationServiceTest.java
- library/javatests/net/openid/appauth/TokenRequestTest.java
After this, we can remove all parameter related code from AuthorizationService.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/2)
> Move token request URI generation into TokenRequest

- library/java/net/openid/appauth/AuthorizationException.java
- library/java/net/openid/appauth/AuthorizationResponse.java
- library/java/net/openid/appauth/AuthorizationService.java
- library/java/net/openid/appauth/TokenResponse.java
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/8)
> More codacy issue fixes

- library/java/net/openid/appauth/AuthorizationService.java
- library/javatests/net/openid/appauth/AuthorizationServiceTest.java
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/10)
> Remove old constants from AuthorizationService, clean up tests

- library/java/net/openid/appauth/AuthState.java
- library/java/net/openid/appauth/AuthorizationException.java
- library/java/net/openid/appauth/AuthorizationResponse.java
- library/java/net/openid/appauth/TokenRequest.java
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/9)
> Consistently use static imports for Precondition checks

- library/java/net/openid/appauth/AdditionalParamsProcessor.java
- library/java/net/openid/appauth/AuthorizationRequest.java
- library/java/net/openid/appauth/AuthorizationResponse.java
- library/java/net/openid/appauth/JsonUtil.java
- library/java/net/openid/appauth/Preconditions.java
- library/java/net/openid/appauth/TokenRequest.java
- library/java/net/openid/appauth/TokenResponse.java
- library/java/net/openid/appauth/UriUtil.java
- library/javatests/net/openid/appauth/AuthorizationRequestTest.java
- library/javatests/net/openid/appauth/AuthorizationResponseTest.java
- library/javatests/net/openid/appauth/PreconditionsTest.java
- library/javatests/net/openid/appauth/TokenRequestTest.java
- library/javatests/net/openid/appauth/TokenResponseTest.java
Make sure that additional parameters do not conflict with built-in
parameters in the builders of request and response types.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/11)
> Check additional parameters

- README.md
- app/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/30)
> Added documentation for adding intents to the AndroidManifest.xml.

- library/java/net/openid/appauth/AsciiStringListUtil.java
- library/java/net/openid/appauth/AuthState.java
- library/java/net/openid/appauth/AuthorizationRequest.java
- library/java/net/openid/appauth/AuthorizationResponse.java
- library/java/net/openid/appauth/TokenRequest.java
- library/java/net/openid/appauth/TokenResponse.java
- library/javatests/net/openid/appauth/AsciiStringListUtilTest.java
- library/javatests/net/openid/appauth/AuthorizationRequestTest.java
Implementation for #14 
+@tikurahul +@WilliamDenniss for review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/31) &emsp; Multiple assignees:&emsp;<img alt="@WilliamDenniss" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/445150?s=40&v=3">&nbsp;<a href="/openid/appauth-android/pulls/assigned/WilliamDenniss">WilliamDenniss</a>,&emsp;<img alt="@tikurahul" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/624211?s=40&v=3">&nbsp;<a href="/openid/appauth-android/pulls/assigned/tikurahul">tikurahul</a>
> Add support for OpenID Connect 1.0 prompt param

- library/java/net/openid/appauth/AuthorizationRequest.java
- library/javatests/net/openid/appauth/AuthorizationRequestTest.java
Implements #13
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/33) &emsp; Multiple assignees:&emsp;<img alt="@WilliamDenniss" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/445150?s=40&v=3">&nbsp;<a href="/openid/appauth-android/pulls/assigned/WilliamDenniss">WilliamDenniss</a>,&emsp;<img alt="@tikurahul" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/624211?s=40&v=3">&nbsp;<a href="/openid/appauth-android/pulls/assigned/tikurahul">tikurahul</a>
> Add support for OpenID Connect 1.0 display param

- library/java/net/openid/appauth/AuthState.java
- library/javatests/net/openid/appauth/AuthStateTest.java
Fix for #26.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/38) &emsp; Multiple assignees:&emsp;<img alt="@WilliamDenniss" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/445150?s=40&v=3">&nbsp;<a href="/openid/appauth-android/pulls/assigned/WilliamDenniss">WilliamDenniss</a>,&emsp;<img alt="@tikurahul" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/624211?s=40&v=3">&nbsp;<a href="/openid/appauth-android/pulls/assigned/tikurahul">tikurahul</a>
> Store OAuth related authorization exceptions on updates

- CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/44)
> Added contributing instructions.

- library/java/net/openid/appauth/AuthorizationResponse.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/43)
> Fix typo in AuthorizationResponse.

- library/java/net/openid/appauth/AuthState.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/42)
> Be more lenient about refresh tokens

- config/checkstyle/checkstyle.xml
- config/checkstyle/java.header
- config/checkstyle/java.header.noregex
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/48)
> Permit 2016 as a copyright year

- build.gradle
- library/java/net/openid/appauth/RedirectUriReceiverActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/52)
> Upgrade Android gradle plugin version

- library/java/net/openid/appauth/AuthState.java
Use the variable names as defined in the signature in the message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/56)
> Improve error message in AuthState.update.

- app/src/net/openid/appauthdemo/TokenActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/57)
> Critical: Handle token refresh request without client auth.

- library/javatests/net/openid/appauth/AuthStateTest.java
Just a typo fix to test the correct behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/55)
> Compare restored state against original state.

- library/java/net/openid/appauth/AuthorizationRequest.java
- library/javatests/net/openid/appauth/AuthStateTest.java
- library/javatests/net/openid/appauth/AuthorizationRequestTest.java
- library/javatests/net/openid/appauth/TestValues.java
Refactoring values to logically group them, similar
to Display and Prompt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/63)
> Move scope values to inner class

- library/java/net/openid/appauth/AuthorizationRequest.java
- library/javatests/net/openid/appauth/AuthorizationRequestTest.java
Refactoring values to logically group them, similar to Display and Prompt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/64)
> Move response mode values to inner class

- README.md
Should not be merged until a new version is released (where `ResponseTypeValues` is included).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/67)
> Update Authorization example in README.

- README.md
Should not be merged until a new version is released (where the dynamic client registration is included).
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/66)
> Add example of dynamic client registration in README.

- README.md
AuthorizationServiceConfiguration.fetchFromIssuer has no return value.
Only use variable in scope in log message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/65)
> Update Configuration example in README.

- CONTRIBUTORS
@tikurahul
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/74)
> Adding Rahul to the CONTRIBUTORS list.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/77)
> Add link to enterprise SSO video

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/78)
> Add example of client auth in token request.

- CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/81)
> Updated CONTRIBUTING now that electronic signing is available.

- app/lint.xml
- config/android-common.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/97)
> Disable old library version checks; we periodically update these manually

- app/java/net/openid/appauthdemo/MainActivity.java
- app/res/layout/activity_main.xml
- app/res/values/strings.xml
- library/java/net/openid/appauth/AuthorizationRequest.java
- library/javatests/net/openid/appauth/AuthorizationRequestTest.java
- library/javatests/net/openid/appauth/TestValues.java
Implementation for #18.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/108)
> Support for login_hint parameter

- library/java/net/openid/appauth/AuthorizationService.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/117)
> Remove duplicate scope constants (moved to AuthorizationRequest)

- library/java/net/openid/appauth/browser/BrowserSelector.java
Should fix #124.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/125)
> Extra flag required to retrieve all browsers on M+

- library/java/net/openid/appauth/TokenResponse.java
- library/javatests/net/openid/appauth/AuthorizationResponseTest.java
- library/javatests/net/openid/appauth/TokenResponseTest.java
Added scope parsing to fromResponseJson(...) as it is missing from parsing causing TokenResponse to lose scope values
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/131)
> Added scope parsing to TokenResponse

- README.md
- library/java/net/openid/appauth/AuthorizationManagementActivity.java
- library/javatests/net/openid/appauth/AuthorizationManagementActivityTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/133)
> Provide response URI on completion

- app/README.md
line 55: an -> a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/126)
> Spelling mistake

- library/javatests/net/openid/appauth/browser/ExactBrowserMatcherTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/152)
> Tests for ExactBrowserMatcher

- library/java/net/openid/appauth/AsciiStringListUtil.java
- library/java/net/openid/appauth/CodeVerifierUtil.java
- library/java/net/openid/appauth/GrantTypeValues.java
- library/java/net/openid/appauth/JsonUtil.java
- library/java/net/openid/appauth/NoClientAuthentication.java
- library/java/net/openid/appauth/Preconditions.java
- library/java/net/openid/appauth/ResponseTypeValues.java
- library/java/net/openid/appauth/UriUtil.java
- library/java/net/openid/appauth/Utils.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/151)
> Explicitly reject construction of non-constructable types

- app/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-android/169)
> Fix IdentityProvider declaration error

- app/java/net/openid/appauthdemo/LoginActivity.java
- app/java/net/openid/appauthdemo/TokenActivity.java
- app/java/net/openid/appauthdemo/package-info.java
Removed some Google specific references that were missed, and
improved the internal documentation of the demo activities to make
their behavior easier to follow.
> Demo app documentation cleanup

- README.md
https://tools.ietf.org/html/draft-ietf-oauth-native-apps-07#section-3
> Replace your-custom-scheme by "reverse domain name notation"

- app/java/net/openid/appauthdemo/LoginActivity.java
- library/java/net/openid/appauth/AuthState.java
- library/java/net/openid/appauth/AuthorizationManagementActivity.java
- library/java/net/openid/appauth/AuthorizationRequest.java
- library/java/net/openid/appauth/AuthorizationResponse.java
- library/java/net/openid/appauth/AuthorizationService.java
- library/java/net/openid/appauth/AuthorizationServiceConfiguration.java
- library/java/net/openid/appauth/CodeVerifierUtil.java
- library/java/net/openid/appauth/browser/CustomTabManager.java
- library/java/net/openid/appauth/internal/Logger.java
- library/java/net/openid/appauth/internal/UriUtil.java
- library/java/net/openid/appauth/internal/package-info.java
- library/javatests/net/openid/appauth/AuthorizationServiceTest.java
- library/javatests/net/openid/appauth/browser/CustomTabManagerTest.java
- library/javatests/net/openid/appauth/internal/LoggerTest.java
- library/javatests/net/openid/appauth/internal/UriUtilTest.java
Addition of methods to warm up the browser with specific URIs, which can help speed up the authorization flow.
Fixed #162.
> Greater control over custom tab session creation

- app/README-Okta.md
- app/README.md
Added a simple howto on configuring the AppAuth for the Okta end points
> added the Okta howto

- .travis.yml
We're replacing Bitrise with Travis.
> Add Travis build configuration

- AUTHORS
For the time being I am acting as an individual contributor
to AppAuth, owning (and transferring) the copyright to my
changes.
> Add myself to the AUTHORS file

- library/java/net/openid/appauth/AuthState.java
- library/javatests/net/openid/appauth/AuthStateTest.java
Fix errors detected by stricter enforcement
> Fix compilation errors in AuthState(Test)

- library/java/net/openid/appauth/browser/CustomTabManager.java
- library/javatests/net/openid/appauth/browser/CustomTabManagerTest.java
> Handle CustomTabsSession.newSession failures

- library/java/net/openid/appauth/AuthorizationService.java
- library/javatests/net/openid/appauth/AuthorizationServiceTest.java
> Do not override tab title setting

- CONTRIBUTORS
- library/java/net/openid/appauth/browser/BrowserBlacklist.java
- library/java/net/openid/appauth/browser/Browsers.java
- library/java/net/openid/appauth/browser/VersionedBrowserMatcher.java
- library/javatests/net/openid/appauth/browser/BrowserWhitelistTest.java
Branch only including the Firefox custom tabs support.
Based on the comments from https://github.com/openid/AppAuth-Android/pull/369
> Firefox customtabs

- index.html
Fixed README.md redirect URL
Closes #528
> Fixed README.md redirect URL

- README.md
- app/README-Okta.md
- app/README.md
- app/java/net/openid/appauthdemo/Configuration.java
- app/java/net/openid/appauthdemo/LoginActivity.java
- app/java/net/openid/appauthdemo/TokenActivity.java
- app/res/raw/auth_config.json
- library/java/net/openid/appauth/AuthorizationManagementActivity.java
- library/java/net/openid/appauth/AuthorizationManagementRequest.java
- library/java/net/openid/appauth/AuthorizationManagementResponse.java
- library/java/net/openid/appauth/AuthorizationManagementUtil.java
- library/java/net/openid/appauth/AuthorizationRequest.java
- library/java/net/openid/appauth/AuthorizationResponse.java
- library/java/net/openid/appauth/AuthorizationService.java
- library/java/net/openid/appauth/AuthorizationServiceConfiguration.java
- library/java/net/openid/appauth/AuthorizationServiceDiscovery.java
- library/java/net/openid/appauth/EndSessionRequest.java
- library/java/net/openid/appauth/EndSessionResponse.java
- library/java/net/openid/appauth/RegistrationRequest.java
- library/java/net/openid/appauth/TokenRequest.java
- library/javatests/net/openid/appauth/AuthorizationManagementActivityTest.java
- library/javatests/net/openid/appauth/AuthorizationServiceConfigurationTest.java
- library/javatests/net/openid/appauth/AuthorizationServiceDiscoveryTest.java
- library/javatests/net/openid/appauth/AuthorizationServiceTest.java
- library/javatests/net/openid/appauth/EndSessionRequestTest.java
- library/javatests/net/openid/appauth/EndSessionResponseTest.java
- library/javatests/net/openid/appauth/IdTokenTest.java
- library/javatests/net/openid/appauth/TestValues.java
Original-author: Sergiy Mokiyenko <smokiyenko@lohika.com>
See: https://github.com/openid/AppAuth-Android/pull/433
Needed the changes so I cleaned the original PR and applied existing patterns in order to match current code design.
> Add end session support

- library/java/net/openid/appauth/AuthorizationServiceConfiguration.java
Add `fetchFromIssuer` with `ConnectionBuilder` parameter for `AuthorizationServiceConfiguration`.
> Add fetchFromIssuer with ConnectionBuilder parameter

- library/java/net/openid/appauth/AuthorizationRequest.java
- library/java/net/openid/appauth/EndSessionRequest.java
- library/javatests/net/openid/appauth/AuthorizationRequestTest.java
- library/javatests/net/openid/appauth/EndSessionRequestTest.java
> Implement ui_locales parameter support.

- app/README.md
> Fixing end_session_uri typo
